In [ ]:
# HEALTHCARE DATA ANALYSIS FOR READMISSION
# Data Cleaning

This project focuses on analyzing healthcare data to understand the factors associated with patient readmission. The dataset contains information about patients, hospital admissions, medical conditions, treatment details, and readmission status. The first stage of the project involves cleaning and preprocessing the dataset by identifying missing values, duplicate records, inconsistent data, and incorrect data types. The cleaned dataset will provide a reliable foundation for further analysis and visualization of healthcare readmission patterns.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/Healthcare Data Analysis for readmission.csv")

df.head()

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,30-01-2024,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,14-07-2024,19-07-2024,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,20-03-2022,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,19-07-2024,07/07/2024,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,13-07-2021,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,20-07-2024,29-06-2024,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,26-01-2021,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,25-06-2024,16-07-2024,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,06/02/2024,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,21-07-2024,19-07-2024,Cancer,16,Transferred,1

Import Libraries & Load Dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   hospital_name            10000 non-null  object
 1   Admission_date           10000 non-null  object
 2   hospital_id              10000 non-null  int64
 3   hospital_beds_available  10000 non-null  int64
 4   occupied_beds            10000 non-null  int64
 5   hospital_ward            10000 non-null  object
 6   patient_id               10000 non-null  int64
 7   patient_gender           10000 non-null  object
 8   patient_age              10000 non-null  int64
 9   patient_race             10000 non-null  object
 10  patient_sat_score        10000 non-null  int64
 11  patient_first_initial    10000 non-null  object
 12  patient_last_name        10000 non-null  object
 13  patient_waittime         10000 non-null  int64
 14  department_referral      10000 non-null  object
 15  time_slot                10000 non-null  object
 16  doctor_id                10000 non-null  int64
 17  doctor_name              10000 non-null  object
 18  doctor_specialty         10000 non-null  object
 19  patient_assigned_doctor  10000 non-null  bool
 20  patient_checkin_date     10000 non-null  object
 21  patient_checkout_date    10000 non-null  object
 22  patient_disease          10000 non-null  object
 23  patient_length_of_stay   10000 non-null  int64
 24  discharge_status         10000 non-null  object
 25  readmission              10000 non-null  int64
dtypes: bool(1), int64(10), object(15)
memory usage: 1.9+ MB

Step 3: Check for Missing Values

In [ ]:
df.isnull().sum()

hospital_name              0
Admission_date             0
hospital_id                0
hospital_beds_available    0
occupied_beds              0
hospital_ward              0
patient_id                 0
patient_gender             0
patient_age                0
patient_race               0
patient_sat_score          0
patient_first_initial      0
patient_last_name          0
patient_waittime           0
department_referral        0
time_slot                  0
doctor_id                  0
doctor_name                0
doctor_specialty           0
patient_assigned_doctor    0
patient_checkin_date       0
patient_checkout_date      0
patient_disease            0
patient_length_of_stay     0
discharge_status           0
readmission                0
dtype: int64

Step 4: Check for Duplicate Records

In [ ]:
df.duplicated().sum()

np.int64(0)

[10:56 am, 17/08/2026] Malavika Entry: Step 5: Check Data Types
[10:56 am, 17/08/2026] Malavika Entry: Checking the data types of each column to identify columns that require conversion for accurate analysis.

In [ ]:
df.dtypes

hospital_name              object
Admission_date             object
hospital_id                 int64
hospital_beds_available     int64
occupied_beds               int64
hospital_ward              object
patient_id                  int64
patient_gender             object
patient_age                 int64
patient_race               object
patient_sat_score           int64
patient_first_initial      object
patient_last_name          object
patient_waittime            int64
department_referral        object
time_slot                  object
doctor_id                   int64
doctor_name                object
doctor_specialty           object
patient_assigned_doctor      bool
patient_checkin_date       object
patient_checkout_date      object
patient_disease            object
patient_length_of_stay      int64
discharge_status           object
readmission                 int64
dtype: object

Step 6: Convert Date ColumnsConverting date columns from object format to datetime format to ensure accurate date-based processing and analysis.

In [ ]:
date_columns = [
    'Admission_date',
    'patient_checkin_date',
    'patient_checkout_date'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')

In [ ]:
df.columns.tolist()

['hospital_name',
 'Admission_date',
 'hospital_id',
 'hospital_beds_available',
 'occupied_beds',
 'hospital_ward',
 'patient_id',
 'patient_gender',
 'patient_age',
 'patient_race',
 'patient_sat_score',
 'patient_first_initial',
 'patient_last_name',
 'patient_waittime',
 'department_referral',
 'time_slot',
 'doctor_id',
 'doctor_name',
 'doctor_specialty',
 'patient_assigned_doctor',
 'patient_checkin_date',
 'patient_checkout_date',
 'patient_disease',
 'patient_length_of_stay',
 'discharge_status',
 'readmission']

In [ ]:

df.columns.tolist()

['hospital_name',
 'Admission_date',
 'hospital_id',
 'hospital_beds_available',
 'occupied_beds',
 'hospital_ward',
 'patient_id',
 'patient_gender',
 'patient_age',
 'patient_race',
 'patient_sat_score',
 'patient_first_initial',
 'patient_last_name',
 'patient_waittime',
 'department_referral',
 'time_slot',
 'doctor_id',
 'doctor_name',
 'doctor_specialty',
 'patient_assigned_doctor',
 'patient_checkin_date',
 'patient_checkout_date',
 'patient_disease',
 'patient_length_of_stay',
 'discharge_status',
 'readmission']

Step 7: Check Unique Values

In [ ]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

hospital_name:
['The Johns Hopkins Hospital']

hospital_ward:
['Maternity' 'ICU' 'Pediatrics' 'Surgery' 'ER']

patient_gender:
['Female' 'Male']

patient_race:
['Asian' 'Black' 'Hispanic' 'White' 'Other']

patient_first_initial:
['t' 'i' 'Y' 's' 'o' 'h' 'p' 'K' 'N' 'W' 'v' 'M' 'g' 'j' 'l' 'n' 'I' 'f'
 'z' 'r' 'V' 'e' 'q' 'm' 'T' 'y' 'F' 'D' 'U' 'X' 'B' 'S' 'a' 'A' 'u' 'd'
 'Q' 'O' 'c' 'x' 'Z' 'E' 'b' 'k' 'R' 'L' 'w' 'C' 'J' 'G' 'P' 'H']

patient_last_name:
['Rogers' 'Spencer' 'Hall' 'Rodriguez' 'Duffy' 'Lopez' 'Warren' 'Munoz'
 'Wolf' 'Smith' 'Espinoza' 'Guerrero' 'Carpenter' 'Lee' 'Santiago'
 'Walters' 'Simpson' 'Strong' 'Vargas' 'Harris' 'Walsh' 'Valdez' 'Owens'
 'Thomas' 'Bradford' 'Hernandez' 'Martinez' 'Anderson' 'Hansen' 'Price'
 'Clark' 'Waters' 'Pierce' 'Henderson' 'Ramos' 'Hendrix' 'Tucker' 'Meyer'
 'Bates' 'Lewis' 'Padilla' 'Morris' 'Burns' 'Barker' 'Ward' 'Howard'
 'Davis' 'Chapman' 'Cross' 'Green' 'Powers' 'Grimes' 'Williams' 'Bonilla'
 'Griffith' 'Sanchez' 'Young' 'Walton' 'Kaiser' 'Rubio' 'Gallegos'
 'Oliver' 'Watson' 'Armstrong' 'Garcia' 'Stewart' 'Robinson' 'Roberson'
 'Martin' 'Bass' 'Miller' 'Scott' 'Shaffer' 'Webster' 'Jones' 'Hines'
 'Jensen' 'Sanford' 'Stevenson' 'Lam' 'Rose' 'Thompson' 'Hicks' 'Rocha'
 'Porter' 'Perry' 'Reilly' 'Benson' 'Murphy' 'Ramirez' 'Jimenez' 'Herrera'
 'Shelton' 'Lucas' 'Hawkins' 'Marshall' 'Jefferson' 'Cannon' 'Johnson'
 'Gutierrez' 'Dunn' 'Cooper' 'Stanley' 'Luna' 'Robertson' 'Wagner'
 'Peters' 'Cortez' 'Schmidt' 'Brooks' 'Adams' 'Miranda' 'Dawson' 'West'
 'Torres' 'Moore' 'Ball' 'Conway' 'Meyers' 'Hartman' 'Hardy' 'Flynn'
 'Coleman' 'Washington' 'Potter' 'White' 'Hoover' 'Banks' 'Mccormick'
 'Nichols' 'Baker' 'Freeman' 'Bender' 'Ellison' 'Reed' 'Allen' 'Perez'
 'Faulkner' 'Gamble' 'Patton' 'Riggs' 'Gonzalez' 'Mccarty' 'Ross'
 'Schneider' 'Taylor' 'Moses' 'Perkins' 'Mitchell' 'Moran' 'Butler' 'Khan'
 'Koch' 'Rangel' 'Davidson' 'Cook' 'Rush' 'Wiley' 'Hill' 'Gordon' 'Henry'
 'Whitaker' 'Lane' 'Parks' 'Daniels' 'Phillips' 'Mcmahon' 'Carey' 'Bryan'
 'Flores' 'Welch' 'Huffman' 'Castillo' 'Osborne' 'Turner' 'Ellis' 'Bell'
 'Michael' 'Drake' 'Clayton' 'Myers' 'Brown' 'Bryant' 'Golden' 'Jackson'
 'Cooke' 'Blackburn' 'Larson' 'Murillo' 'Mack' 'Wilson' 'Trevino'
 'Morrison' 'Mann' 'Harper' 'Sweeney' 'Boyer' 'Lynch' 'Arroyo' 'Mcdowell'
 'Hays' 'Aguirre' 'Rasmussen' 'Steele' 'Graham' 'Pitts' 'Calderon' 'Gill'
 'Stone' 'Fleming' 'Woodard' 'Hughes' 'Shepherd' 'Hunt' 'Vasquez'
 'Roberts' 'Ortiz' 'Moss' 'Bowers' 'Griffin' 'Wade' 'Rosario' 'Choi'
 'Ritter' 'Hanson' 'Caldwell' 'Ferguson' 'Aguilar' 'Garza' 'Frederick'
 'Wood' 'Diaz' 'Love' 'Watkins' 'Sanders' 'Cunningham' 'Morgan' 'Wallace'
 'Barnes' 'Wells' 'Macdonald' 'Randolph' 'Hunter' 'Reid' 'Stevens'
 'Jenkins' 'Nelson' 'Keller' 'Nash' 'Gomez' 'Carney' 'Lowery' 'Francis'
 'David' 'Simmons' 'Rhodes' 'Chen' 'Cummings' 'Bennett' 'Cohen' 'Vincent'
 'Holden' 'Riley' 'Graves' 'Villarreal' 'Page' 'Harrison' 'Blanchard'
 'Alvarez' 'Leonard' 'King' 'Fitzgerald' 'Schmitt' 'Travis' 'Reyes'
 'Guerra' 'Hamilton' 'Reeves' 'Andersen' 'Woodward' 'Poole' 'Mcgee'
 'Parker' 'Harvey' 'Olsen' 'Pollard' 'Flowers' 'Landry' 'Ryan' 'Warner'
 'Keith' 'Collins' 'Grant' 'Villanueva' 'Bishop' 'Small' 'Pineda' 'Chavez'
 'Walker' 'Obrien' 'Pace' 'Sutton' 'Mccarthy' 'Frost' 'Zimmerman'
 'Dougherty' 'Hale' 'Jordan' 'Harmon' 'Summers' 'Terry' 'Hart' 'Douglas'
 'Costa' 'Wheeler' 'Fernandez' 'Campbell' 'Powell' 'Boone' 'Goodman'
 'Pugh' 'Gregory' 'Duran' 'Chan' 'Mcclain' 'Knapp' 'Simon' 'Richards'
 'Gibbs' 'Carter' 'Matthews' 'Cox' 'Neal' 'Rivera' 'Benitez' 'Chambers'
 'Casey' 'Murray' 'Byrd' 'Whitehead' 'Richard' 'Mcdaniel' 'Cabrera' 'Duke'
 'Dudley' 'Werner' 'Crawford' 'Ayala' 'Boyle' 'Daugherty' 'Kelly'
 'Ballard' 'Franklin' 'Huber' 'Cowan' 'Jacobs' 'Gross' 'Herring'
 'Thornton' 'Stark' 'Bernard' 'Terrell' 'Barr' 'Dixon' 'Branch' 'Doyle'
 'Richardson' 'Friedman' 'Sawyer' 'Church' 'Benjamin' 'Gibson' 'Huang'
 'Stanton' 'Pearson' 'Hubbard' 'Pena' 'Hahn' 'Weber' 'Peterson' 'Boyd'
 'Fisher' 'Beard' 'Foster' 'Paul' 'Copeland' 'Santana' 'Camacho' 'Good'
 'Roy' 'Fields' 'Gates' 'Kerr' 'Hodges' 'Bradley' 'Mclaughlin'
 'Blankenship' 'Fowler' 'Edwards' 'Lloyd' 'Shaw' 'Pham' 'Mcdonald' 'Tran'
 'Fry' 'Carlson' 'Goodwin' 'Holmes' 'George' 'Stuart' 'Bailey' 'Gardner'
 'Walter' 'Cain' 'Bowman' 'Gonzales' 'Durham' 'Whitney' 'Manning' 'Avery'
 'Colon' 'Howell' 'Mahoney' 'Wolfe' 'Robles' 'Ortega' 'Hayden' 'Conner'
 'Gay' 'Barajas' 'Romero' 'Barton' 'Greene' 'Foley' 'Mendoza' 'Wilkinson'
 'Kelley' 'Erickson' 'Hooper' 'Adkins' 'Lyons' 'Mclean' 'Donaldson'
 'Kennedy' 'James' 'Holland' 'Le' 'York' 'Day' 'Elliott' 'Christensen'
 'Vaughn' 'Palmer' 'Webb' 'French' 'Carson' 'Sullivan' 'Chase' 'Walls'
 'Li' 'Kramer' 'Hancock' 'Bird' 'Burton' 'Joseph' 'Barnett' 'Long'
 'Barrett' 'Soto' 'Mueller' 'Becker' 'Peck' 'Hebert' 'Ruiz' 'Rivers'
 'Blackwell' 'Morales' 'Massey' 'Wyatt' 'Compton' 'Weiss' 'Fox' 'Dickson'
 'Newton' 'Snow' 'Berry' 'Melendez' 'Mora' 'Hinton' 'Ray' 'Norman' 'Gould'
 'Reynolds' 'Clements' 'Cruz' 'Dominguez' 'Schultz' 'Cantu' 'Tyler'
 'Evans' 'Davies' 'Strickland' 'Curry' 'Davila' 'Allison' 'Quinn' 'Meza'
 'Irwin' 'Kim' 'Dickerson' 'Horton' 'Daniel' 'Gray' 'Stout' 'Johnston'
 'Melton' 'Pratt' 'Vega' 'Solis' 'Carr' 'Anthony' 'Klein' 'Russell' 'Shea'
 'Cuevas' 'Kent' 'Lang' 'Salazar' 'Navarro' 'Barrera' 'Harrell' 'Austin'
 'Sims' 'Weaver' 'Duncan' 'Mccall' 'Trujillo' 'Higgins' 'Mosley'
 'Patterson' 'Glenn' 'Noble' 'Baldwin' 'Benton' 'Nguyen' 'Lin' 'Mason'
 'Baxter' 'Briggs' 'Frye' 'Bush' 'English' 'Herman' 'Montgomery' 'Charles'
 'Beck' 'Hayes' 'Sherman' 'Patel' 'Howe' 'Santos' 'Snyder' 'Frazier'
 'Newman' 'Dillon' 'Stafford' 'Rodgers' 'Molina' 'Mullins' 'Savage'
 'Chandler' 'Valencia' 'Mckenzie' 'Rich' 'Maxwell' 'Morton' 'Hoffman'
 'Lawson' 'Bright' 'Hopkins' 'Olson' 'Bullock' 'Haynes' 'Berg' 'Parrish'
 'Leon' 'Bruce' 'Mckee' 'Raymond' 'Hanna' 'Wilkerson' 'Juarez' 'Vance'
 'Alexander' 'Swanson' 'Cline' 'May' 'Payne' 'Wall' 'Donovan' 'Fischer'
 'Osborn' 'Floyd' 'Clay' 'Campos' 'Castro' 'Valentine' 'Miles' 'Watts'
 'Moreno' 'Malone' 'Combs' 'Ewing' 'Hickman' 'Gilbert' 'Avila' 'Lamb'
 'Craig' 'Mcguire' 'Morrow' 'Meadows' 'Mcconnell' 'Maldonado' 'Oneal'
 'Velasquez' 'Carroll' 'Merritt' 'Decker' 'Mendez' 'Black' 'Joyce'
 'Hammond' 'Rosales' 'Sharp' 'Pacheco' 'Hampton' 'Rowe' 'Rios' 'Nicholson'
 'Humphrey' 'Garrett' 'Medina' 'Delgado' 'Finley' 'Cameron' 'Little'
 'Hendricks' 'Fletcher' 'Randall' 'Townsend' 'Glass' 'Villegas' 'Conley'
 'Sheppard' 'Rice' 'Booth' 'Bauer' 'Parsons' 'Wilkins' 'Wise' 'Mccann'
 'Wang' 'Brewer' 'Guzman' 'Rollins' 'Berger' 'Velez' 'Fuller' 'Gallagher'
 'Gillespie' 'Lawrence' 'Hess' 'Pennington' 'Williamson' 'Burgess' 'Wu'
 'Moody' 'Garrison' 'Park' 'Salinas' 'Silva' 'Orr' 'Buchanan' 'Patrick'
 'Chang' 'Eaton' 'Sosa' 'Everett' 'Brandt' 'Barry' 'Saunders' 'Wright'
 'Holloway' 'Contreras' 'Atkins' 'Acosta' 'Lynn' 'Mills' 'Potts' 'Serrano'
 'Blevins' 'Mays' 'Huynh' 'Best' 'Stephens' 'Ramsey' 'Esparza' 'Leach'
 'Petty' 'Oconnor' 'Estrada' 'House' 'Salas' 'Dorsey' 'Mayo' 'Nielsen'
 'Mejia' 'Farley' 'Hogan' 'Andrade' 'Galloway' 'Clarke' 'Crane' 'Figueroa'
 'Schwartz' 'Wong' 'Kline' 'Willis' 'Weeks' 'Woods' 'Braun' 'Yu' 'Abbott'
 'Nixon' 'Bautista' 'Andrews' 'Buckley' 'Mckay' 'Cole' 'Case' 'Leblanc'
 'Jennings' 'Petersen' 'Knox' 'Tate' 'Ali' 'Arnold' 'Delacruz' 'Fuentes'
 'Marquez' 'Glover' 'Frank' 'Ford' 'Shields' 'Beasley' 'Bridges' 'Ponce'
 'Cervantes' 'Shannon' 'Shah' 'Logan' 'Richmond' 'Dunlap' 'Montes'
 'Mathews' 'Dennis' 'Riddle' 'Larsen' 'Giles' 'Hardin' 'Macias' 'Huff'
 'Marsh' 'Brady' 'Kirby' 'Odonnell' 'Norris' 'Mcclure' 'Curtis' 'Lutz'
 'Mcpherson' 'Brennan' 'Maddox' 'Moyer' 'Solomon' 'Mcintosh' 'Orozco'
 'Burnett' 'Estes' 'Kidd' 'Ochoa' 'Blake' 'Liu' 'Yoder' 'Hudson' 'Brock'
 'Zavala' 'Farrell' 'Livingston' 'Mccullough' 'Mcbride' 'Burch' 'Mayer'
 'Burke' 'Chung' 'Bond' 'Cobb' 'Phelps' 'Skinner' 'Stein' 'Beltran'
 'Mcfarland' 'Hurst' 'Maynard' 'Rojas' 'Callahan' 'Buck' 'Downs' 'Zamora'
 'Sampson' 'Sandoval' 'Mathis' 'Nunez' 'Short' 'Roach' 'Blair' 'Cordova'
 'Conrad' 'Dyer' 'Gaines' 'Madden' 'Winters' 'Kirk' 'Greer' 'Robbins'
 'Mccoy' 'Galvan' 'Key' 'Russo' 'Mcknight' 'Underwood' 'Monroe' 'Krueger'
 'Kane' 'Yates' 'Hodge' 'Arias' 'Holt' 'Tapia' 'Ware' 'Heath' 'Hurley'
 'Tanner' 'Cooley' 'Haley' 'Holder' 'Mckinney' 'Henson' 'Zuniga' 'Sloan'
 'Ibarra' 'Villa' 'Christian' 'Ho' 'Atkinson' 'Lowe' 'Roth' 'Vazquez'
 'Pope' 'Bartlett' 'Roman' 'Deleon' 'Baird' 'Collier' 'Oconnell' 'Moon'
 'Yang' 'Wilcox' 'Calhoun' 'Garner' 'Booker' 'Harrington' 'Lambert'
 'Duarte' 'Sellers' 'Fritz' 'Escobar' 'Ingram' 'Prince' 'Barber' 'Barron'
 'Bradshaw' 'Bowen' 'Pruitt' 'Bentley' 'Lozano' 'Arellano' 'Suarez'
 'Novak' 'Stephenson' 'Waller' 'Lindsey' 'Mercado' 'Ayers' 'Horn'
 'Cardenas' 'Gilmore' 'Hull' 'Castaneda' 'Singh' 'Hood' 'Lara' 'Acevedo'
 'Dean' 'Franco' 'Vang' 'Dalton' 'Carrillo' 'Vaughan' 'Sparks' 'Ashley'
 'Hutchinson' 'Sexton' 'Jacobson' 'Norton' 'Oneill' 'Rivas' 'Mercer'
 'Bean' 'Spears' 'Crosby' 'Krause' 'Owen' 'Ferrell' 'Knight' 'Preston'
 'Kemp' 'Gentry' 'Hatfield' 'Spence' 'Cochran' 'Farmer' 'Wiggins' 'Marks'
 'Singleton' 'Pittman' 'Todd' 'Chaney' 'Hester' 'Dodson' 'Velazquez'
 'Valenzuela' 'Stokes' 'Nolan' 'Forbes' 'Lester' 'Browning' 'Odom'
 'Mcneil' 'Fitzpatrick' 'Houston' 'Mcgrath' 'Mcintyre' 'Reese' 'Archer'
 'Shepard' 'Middleton' 'Montoya' 'Frey' 'Alvarado' 'Mullen' 'Harding'
 'Haas' 'Horne' 'Cantrell' 'Huerta' 'Hensley' 'Cisneros' 'Schroeder'
 'Mata' 'Mooney' 'Davenport' 'Mcmillan' 'Coffey' 'Levine']

department_referral:
['Urology or Nephrology' 'Neurology' 'Gastroenterology' 'Dermatology'
 'Infectious Disease or Internal Medicine' 'Allergy and Immunology'
 'Psychiatry' 'Infectious Disease' 'Nephrology' 'Cardiology'
 'Rheumatology' 'Cardiology or Internal Medicine' 'Oncology'
 'Pulmonology or Allergy and Immunology' 'Hepatology or Gastroenterology'
 'Endocrinology' 'Hepatology' 'Pulmonology'
 'Pulmonology or Infectious Disease']

time_slot:
['02:34:00 PM' '04:07:00 PM' '07:16:00 PM' ... '10:34:00 AM' '09:15:00 PM'
 '11:37:00 PM']

doctor_name:
['Justin Morris' 'Latoya Moss' 'Michael Allen' ... 'Richard Turner'
 'Jonathan Thompson' 'Louis Luna MD']

doctor_specialty:
['Rheumatology' 'Pulmonology or Allergy and Immunology' 'Neurology'
 'Cardiology' 'Pulmonology or Infectious Disease' 'Gastroenterology'
 'Cardiology or Internal Medicine' 'Oncology' 'Dermatology'
 'Infectious Disease or Internal Medicine' 'Psychiatry'
 'Allergy and Immunology' 'Hepatology' 'Infectious Disease'
 'Endocrinology' 'Pulmonology' 'Nephrology'
 'Hepatology or Gastroenterology' 'Urology or Nephrology']

patient_disease:
['Anxiety Disorders' 'Urinary Tract Infection (UTI)'
 'Hypertension (High Blood Pressure)' 'Arthritis' 'Cancer'
 'Chronic Kidney Disease' 'Migraine' 'Heart Disease'
 'Irritable Bowel Syndrome (IBS)' 'Hepatitis' 'Epilepsy' 'Pneumonia'
 'Influenza (Flu)' 'Diabetes' 'Parkinson’s Disease' 'HIV/AIDS'
 'Skin Diseases' 'Chronic Obstructive Pulmonary Disease (COPD)'
 'Liver Cirrhosis' 'COVID-19' 'Gastroesophageal Reflux Disease (GERD)'
 'Allergic Rhinitis (Hay Fever)' 'Alzheimer’s Disease' 'Stroke'
 'Depression' 'Autoimmune Diseases' 'Celiac Disease' 'Asthma']

discharge_status:
['Deceased' 'Recovered' 'Transferred']

In [ ]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print(f"{col}: {df[col].nunique()} unique values")

hospital_name: 1 unique values
hospital_ward: 5 unique values
patient_gender: 2 unique values
patient_race: 5 unique values
patient_first_initial: 52 unique values
patient_last_name: 985 unique values
department_referral: 19 unique values
time_slot: 1439 unique values
doctor_name: 9379 unique values
doctor_specialty: 19 unique values
patient_disease: 28 unique values
discharge_status: 3 unique values

Step 8: Check Numerical Columns

In [ ]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Admission_date,6081,2022-07-15 19:48:59.319191040,2020-07-24 00:00:00,2021-07-17 00:00:00,2022-07-14 00:00:00,2023-07-23 00:00:00,2024-07-22 00:00:00,NaN
hospital_id,10000.0,5515.9666,1000.0,3255.75,5516.5,7790.25,9998.0,2605.495574
hospital_beds_available,10000.0,299.111,100.0,200.0,300.0,400.0,500.0,117.973859
occupied_beds,10000.0,199.085,0.0,100.0,200.0,300.0,400.0,118.299418
patient_id,10000.0,5498.7387,1000.0,3232.5,5478.5,7779.5,9999.0,2615.168591
patient_age,10000.0,47.283,0.0,23.0,47.0,71.0,95.0,27.719692
patient_sat_score,10000.0,847.802,100.0,480.0,840.0,1220.0,1600.0,432.952877
patient_waittime,10000.0,67.824,15.0,30.0,75.0,105.0,120.0,34.519765
doctor_id,10000.0,5476.229,1000.0,3178.75,5445.5,7783.0,9998.0,2626.286129
patient_checkin_date,5926,2024-07-08 09:31:02.571717888,2024-06-23 00:00:00,2024-06-27 00:00:00,2024-07-14 00:00:00,2024-07-18 00:00:00,2024-07-22 00:00:00,NaN
patient_checkout_date,5873,2024-07-08 23:57:47.597479936,2024-06-24 00:00:00,2024-06-28 00:00:00,2024-07-14 00:00:00,2024-07-18 00:00:00,2024-07-22 00:00:00,NaN
patient_length_of_stay,10000.0,15.5065,1.0,8.0,16.0,23.0,30.0,8.611955
readmission,10000.0,0.4142,0.0,0.0,0.0,1.0,1.0,0.492608

Step 9: Check for Negative Values

In [ ]:
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    negative_count = (df[col] < 0).sum()
    print(f"{col}: {negative_count} negative values")

hospital_id: 0 negative values
hospital_beds_available: 0 negative values
occupied_beds: 0 negative values
patient_id: 0 negative values
patient_age: 0 negative values
patient_sat_score: 0 negative values
patient_waittime: 0 negative values
doctor_id: 0 negative values
patient_length_of_stay: 0 negative values
readmission: 0 negative values

step 10: Validate Important Numerical Ranges

In [ ]:
print("Patient Age:")
print(df['patient_age'].min(), df['patient_age'].max())

print("\nPatient Satisfaction Score:")
print(df['patient_sat_score'].min(), df['patient_sat_score'].max())

print("\nReadmission Values:")
print(df['readmission'].unique())

Patient Age:
0 95

Patient Satisfaction Score:
100 1600

Readmission Values:
[1 0]

Step 11: Inspect Suspicious Values

In [ ]:
print("Patient Age values:")
print(df['patient_age'].value_counts().sort_index().head(15))

print("\nPatient Satisfaction Score values:")
print(df['patient_sat_score'].value_counts().sort_index().head(15))

Patient Age values:
patient_age
0      94
1      99
2     118
3     121
4      98
5     107
6     112
7     115
8     107
9     109
10    121
11     97
12    123
13    109
14    107
Name: count, dtype: int64

Patient Satisfaction Score values:
patient_sat_score
100    65
110    54
120    80
130    67
140    56
150    53
160    60
170    71
180    62
190    71
200    61
210    71
220    62
230    70
240    72
Name: count, dtype: int64

Step 12: Check and Remove Extra Spaces
Checking text-based columns for leading or trailing spaces and standardizing the text format for consistency.

In [ ]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
df.head()

,hospital_name,Admission_date,hospital_id,hospital_beds_available,occupied_beds,hospital_ward,patient_id,patient_gender,patient_age,patient_race,...,doctor_id,doctor_name,doctor_specialty,patient_assigned_doctor,patient_checkin_date,patient_checkout_date,patient_disease,patient_length_of_stay,discharge_status,readmission
0,The Johns Hopkins Hospital,2024-01-30,3946,260,90,Maternity,1421,Female,48,Asian,...,1725,Justin Morris,Rheumatology,False,2024-07-14,2024-07-19,Anxiety Disorders,6,Deceased,1
1,The Johns Hopkins Hospital,2022-03-20,7147,250,90,ICU,4922,Male,40,Black,...,7510,Latoya Moss,Pulmonology or Allergy and Immunology,False,2024-07-19,NaT,Urinary Tract Infection (UTI),2,Deceased,1
2,The Johns Hopkins Hospital,2021-07-13,4174,350,220,Pediatrics,9804,Female,74,Black,...,7137,Michael Allen,Neurology,False,2024-07-20,2024-06-29,Hypertension (High Blood Pressure),17,Recovered,0
3,The Johns Hopkins Hospital,2021-01-26,2466,190,350,Pediatrics,5622,Male,82,Hispanic,...,8801,Rebecca Mccullough,Cardiology,False,2024-06-25,2024-07-16,Arthritis,28,Recovered,0
4,The Johns Hopkins Hospital,NaT,3014,220,390,Surgery,3314,Male,62,Hispanic,...,3588,John Giles,Rheumatology,False,2024-07-21,2024-07-19,Cancer,16,Transferred,1

Step 13: Check Invalid Date ValuesChecking the converted date columns for invalid or unrecognized date values represented as NaT.

In [ ]:
print("Patient Age values:")
print(df['patient_age'].value_counts().sort_index().head(15))

print("\nPatient Satisfaction Score values:")
print(df['patient_sat_score'].value_counts().sort_index().head(15))

Patient Age values:
patient_age
0      94
1      99
2     118
3     121
4      98
5     107
6     112
7     115
8     107
9     109
10    121
11     97
12    123
13    109
14    107
Name: count, dtype: int64

Patient Satisfaction Score values:
patient_sat_score
100    65
110    54
120    80
130    67
140    56
150    53
160    60
170    71
180    62
190    71
200    61
210    71
220    62
230    70
240    72
Name: count, dtype: int64

In [ ]:
for col in date_columns:
    print(f"{col}: {df[col].isna().sum()} invalid dates")

Admission_date: 3919 invalid dates
patient_checkin_date: 4074 invalid dates
patient_checkout_date: 4127 invalid dates

Step 13 — Check Original Date Format

In [ ]:
for col in date_columns:
    print(f"\n{col}")
    print(df[col].head(10))

Admission_date
0   2024-01-30
1   2022-03-20
2   2021-07-13
3   2021-01-26
4          NaT
5   2022-04-29
6   2020-07-25
7   2022-05-18
8   2022-07-20
9   2022-05-29
Name: Admission_date, dtype: datetime64[ns]

patient_checkin_date
0   2024-07-14
1   2024-07-19
2   2024-07-20
3   2024-06-25
4   2024-07-21
5          NaT
6   2024-07-21
7   2024-07-19
8          NaT
9   2024-07-14
Name: patient_checkin_date, dtype: datetime64[ns]

patient_checkout_date
0   2024-07-19
1          NaT
2   2024-06-29
3   2024-07-16
4   2024-07-19
5   2024-06-25
6   2024-07-16
7   2024-07-14
8   2024-07-18
9          NaT
Name: patient_checkout_date, dtype: datetime64[ns]

Step 13: Restore and Validate Date     Columns The original dataset already contains the date columns in datetime format. The original data is restored to avoid unnecessary conversion and to preserve the actual missing date values.

In [ ]:
df = original_df.copy()

date_columns = [
    'Admission_date',
    'patient_checkin_date',
    'patient_checkout_date'
]

for col in date_columns:
    print(f"{col}: {df[col].isna().sum()} missing dates")

NameError: name 'original_df' is not defined

In [ ]:
# Reload the original dataset
original_df = pd.read_csv("/content/Healthcare Data Analysis for readmission.csv")

# Restore the original dataset
df = original_df.copy()

# Date columns
date_columns = [
    'Admission_date',
    'patient_checkin_date',
    'patient_checkout_date'
]

# Check missing dates
for col in date_columns:
    print(f"{col}: {df[col].isna().sum()} missing dates")

Admission_date: 0 missing dates
patient_checkin_date: 0 missing dates
patient_checkout_date: 0 missing dates

Step 14: Final Data Quality Check

In [ ]:
print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

Dataset Shape: (10000, 26)

Missing Values:
0

Duplicate Records:
0

In [ ]:
df.to_csv("Healthcare_Data_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.